import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

const Home = () => {
	return (
		<>
			<Head>
				<title>Gurjot Singh</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
				/>
			</Head>

			<Navbar />
		</>
	);
};

export default Home;
